<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $salesPage->product_name }} — Sales Page</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="preconnect" href="https://fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=inter:300,400,500,600,700,800,900&display=swap" rel="stylesheet">
    <style>
        body { font-family: 'Inter', sans-serif; }
        .animate-pulse { animation: pulse 2s cubic-bezier(0.4,0,0.6,1) infinite; }
        @keyframes pulse { 0%,100% { opacity:1; } 50% { opacity:.5; } }
    </style>
</head>
<body>
    @include('sales-pages.partials.preview-' . $salesPage->template, ['salesPage' => $salesPage])

    <footer style="text-align:center;padding:24px;background:#f9fafb;color:#9ca3af;font-size:12px;">
        Generated by AI Sales Page Generator &bull; {{ now()->format('F j, Y') }}
    </footer>
</body>
</html>
